name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tags
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src/Catalog.API
        file: ./src/Catalog.API/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/your-repo-name:${{ steps.get_version.outputs.VERSION }}
