name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_VERSION: 21
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore
        working-directory: src
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src
      - name: List directory contents
        run: ls -al
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install -f
        working-directory: ./
      - name: Print GITHUB_SHA
        run: echo $GITHUB_SHA

      - name: Release
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        working-directory: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tags
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/Catalog.API
          file: ./src/Catalog.API/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/catalog:${{ steps.get_version.outputs.VERSION }}
