name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  USER_NAME: ${{ secrets.USER_NAME }}
  NODE_VERSION: 21
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install -f
        working-directory: ./

      - name: Print GITHUB_SHA
        run: echo $GITHUB_SHA

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: npx semantic-release
        working-directory: ./
